{
  "schema_version": "1.4.0",
  "id": "GHSA-p8h8-wq9m-5rg2",
  "modified": "2025-01-16T12:30:55Z",
  "published": "2025-01-16T12:30:55Z",
  "aliases": [
    "CVE-2018-25108"
  ],
  "details": "An unauthenticated remote attacker can cause a DoS in the controller due toÂ uncontrolled resource consumption.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2018-25108"
    },
    {
      "type": "WEB",
      "url": "https://cert.vde.com/en/advisories/VDE-2018-013"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-770"
    ],
    "severity": "HIGH",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2025-01-16T11:15:06Z"
  }
}