{
  "schema_version": "1.4.0",
  "id": "GHSA-j9m2-4gfx-jq57",
  "modified": "2022-04-19T00:01:29Z",
  "published": "2022-04-11T00:00:22Z",
  "aliases": [
    "CVE-2022-1289"
  ],
  "details": "A denial of service vulnerability was found in tildearrow Furnace. It has been classified as problematic. This is due to an incomplete fix of CVE-2022-1211. It is possible to initiate the attack remotely but it requires user interaction. The issue got fixed with the patch 0eb02422d5161767e9983bdaa5c429762d3477ce.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-1289"
    },
    {
      "type": "WEB",
      "url": "https://github.com/tildearrow/furnace/issues/325#issuecomment-1094139655"
    },
    {
      "type": "WEB",
      "url": "https://github.com/tildearrow/furnace/commit/0eb02422d5161767e9983bdaa5c429762d3477ce"
    },
    {
      "type": "WEB",
      "url": "https://vuldb.com/?id.196755"
    }
  ],
  "database_specific": {
    "cwe_ids": [],
    "severity": "MODERATE",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2022-04-10T16:15:00Z"
  }
}