{
  "schema_version": "1.4.0",
  "id": "GHSA-6q3r-569c-crm7",
  "modified": "2024-12-04T18:32:34Z",
  "published": "2024-12-04T18:32:34Z",
  "aliases": [
    "CVE-2024-53432"
  ],
  "details": "While parsing certain malformed PLY files, PCL version 1.14.1 crashes due to an uncaught std::out_of_range exception in PCLPointCloud2::at. This issue could potentially be exploited to cause a denial-of-service (DoS) attack when processing untrusted PLY files.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-53432"
    },
    {
      "type": "WEB",
      "url": "https://github.com/PointCloudLibrary/pcl/issues/6162"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-754"
    ],
    "severity": "HIGH",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2024-11-21T18:15:14Z"
  }
}